spring:
  datasource:
        url: jdbc:postgresql://localhost:5432/flyway_db
        username: postgres
        password: 5784
        driver-class-name: org.postgresql.Driver
  jpa:
      hibernate:
         ddl-auto: none
      show-sql: true
  main:
    allow-bean-definition-overriding: true