spring:
    main.allow-bean-definition-overriding: true
    datasource:
        url: jdbc:postgresql://localhost:5432/spring_data
        username: postgres
        password: 5784
        driver-class-name: org.postgresql.Driver
    jpa:
      hibernate:
         ddl-auto: none
      show-sql: true